
# This is a special configuration file to run tests on Travis-CI via
# GitHub notifications when changes are committed.
#
# See http://travis-ci.org/ for details
language: python

before_install:
 - export GALAXY_RELEASE=release_17.05
 - export PLANEMO_CONDA_PREFIX="$HOME/conda"
 - sudo apt-get install -y python-virtualenv
 - virtualenv planemo-venv
 - . planemo-venv/bin/activate
 - pip install --upgrade pip setuptools

install:
 - pip install planemo
 - planemo conda_init
 - export PATH="$PLANEMO_CONDA_PREFIX/bin:$PATH"
 - planemo --version
 - conda --version
 - travis_wait 30 planemo conda_install --conda_channels iuc,bioconda,conda-forge,defaults ${TRAVIS_BUILD_DIR}/sartools/

script:
 - planemo test --install_galaxy --no_cache_galaxy --conda_dependency_resolution --conda_channels iuc,bioconda,conda-forge,defaults --galaxy_branch "$GALAXY_RELEASE" ${TRAVIS_BUILD_DIR}/sartools
