categories: [RNA,Statistics,Transcriptomics]
description: SARTools is a R package dedicated to the differential analysis of RNA-seq
  data.
long_description: 'SARTools provides R tools and an environment for the statistical
  analysis of RNA-Seq projects: load and clean data, produce figures, perform statistical
  analysis/testing with DESeq2 or edgeR, export results and create final report.'
homepage_url: https://github.com/PF2-pasteur-fr/SARTools
remote_repository_url: https://github.com/PF2-pasteur-fr/SARTools-Galaxy/tree/master/sartools
name: sartools
owner: lgueguen
